In [2]:
# coding: utf-8 
import sys, os # OSでディレクトリを変更したりするためのパッケージをインポート
#sys.path.append(os.pardir)　#１つ上の階層のディレクトリ内にあるものを読み込めるようにしておけ、という命令（今回はdeep-learning-from-scratch-master）
sys.path.append(os.pardir)

import numpy as np
from dataset.mnist import load_mnist　#mnist.pyの中に書かれている関数を使えるようにしろ、という命令、後半はその中からload_mnistをもってこいと命令
from two_layer_net import TwoLayerNet

# データの読み込み　
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)#番地に名前をつけて、環境変数とした

network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)　#初期化したネットワークを生成

iters_num = 10000　　#繰り返し回数
train_size = x_train.shape[0] #訓練データの数
batch_size = 100　#１つのバッチに入っている訓練データの数
learning_rate = 0.1　#勾配降下する際の掛け率

train_loss_list = []　# ここでは枠だけ作っている
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)　#訓練データ60,000/バッチサイズ１００  600バッチ繰り返し/1epoch

for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size) # 0〜５９，９９９の整数のうち、バッチサイズの数分、ランダムに取り出せ（重複あり）　⭐️
    x_batch = x_train[batch_mask]　#batch_mask できめた番号のデータをx_batch という環境変数に入れる
    t_batch = t_train[batch_mask]　#batch_mask の番号に従った取り出し方をした被説明変数（訓練ラベル）のみのリストで、上の説明変数の順序に対応
    
    # 勾配
    #grad = network.numerical_gradient(x_batch, t_batch)
    grad = network.gradient(x_batch, t_batch)
    
    # 更新
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
    
    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    
    if i % iter_per_epoch == 0:　# イテレーションの数（600バッチ繰り返し）が600の倍数だった場合に以下のことを行え
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)　　#.appendは新しい数字を後ろに加えろ（今回はtrain_acc）
        test_acc_list.append(test_acc)
        print(train_acc, test_acc)

SyntaxError: invalid character in identifier (<ipython-input-2-753e1c1a62bc>, line 7)

In [33]:
np.random.choice(train_size, batch_size)

array([ 8008, 48658, 35648, 35489, 49204, 57844, 42356, 59831, 50527,
       29361, 42654, 40339, 29219, 14832, 59765,  3310, 14413, 10604,
       31005, 54248, 49267, 14935, 35876, 50378, 30792, 27980,  9026,
        9040, 57624, 14659, 56606, 46236, 19104, 39593,  7968, 31804,
        3657, 38704, 42052, 38655, 55714,   829, 18042,  4377,  2669,
       21769, 57364, 37756, 35478, 19865, 55515, 22083, 20649, 43518,
       44141, 58630, 43182, 48300, 35258,  8098, 35876, 35071,  1649,
       50271, 46676, 41753, 58781, 59688, 23096, 11251,  3834, 22447,
       32969, 21777,  4103, 58692, 45635, 50406,  5150, 33766, 22289,
        3998, 18385,  3764, 34591, 26979, 28323, 35963,  9463,   349,
       31318, 49133, 14839, 44147,  4536, 40204, 16010,  1857, 34122,
       42512])

In [37]:
import os
os.getcwd()

'/Users/kensyo/Desktop/deep-learning-from-scratch-master/ch05'

In [29]:
np.random.choice(10, 7)

array([0, 5, 5, 0, 5, 4, 4])

In [26]:
max(train_size / batch_size, 1)

600.0

In [22]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
len( load_mnist()[0][0]) #個数をカウントする場合、len() は１つ下の階層の個数を数える　この場合は丁目と番地を指定しているので何号まであるかを出力

60000

In [11]:
 load_mnist()[0][0][6] #6番目の画像データをピクセルデータとして出力

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
 load_mnist()[0][1][6] #6番目の画像データのラベルをピクセルデータとして出力

1

In [20]:
 load_mnist(normalize=False,flatten=False)[0][0][6].shape

(1, 28, 28)